Traceback (most recent call last):
  File "/lustreFS/data/lear/sathvik/Steel-Defect-Detection/src/decode_RLE.py", line 33, in <module>
    train_df = pd.read_csv(TRAIN_CSV)
  File "/trinity/home/skadimisetty/data/sathvik/miniconda3/envs/defects/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/trinity/home/skadimisetty/data/sathvik/miniconda3/envs/defects/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/trinity/home/skadimisetty/data/sathvik/miniconda3/envs/defects/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/trinity/home/skadimisetty/data/sathvik/miniconda3/envs/defects/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/trinity/home/skadimisetty/data/sathvik/miniconda3/envs/defects/lib/python3.10/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'train.csv'
Your remaining balance (at the time of job end)
User           Usage |        Account     Usage | Account Limit Available (CPU hrs)
---------- --------- + -------------- --------- + ------------- ---------
ggrotto            6 |           LEAR        99 |             0       N/A
ipastellas         4 |           LEAR        99 |             0       N/A
skadimisetty *        89 |           LEAR        99 |             0       N/A
vtsiourtis         1 |           LEAR        99 |             0       N/A
vvassiliades         0 |           LEAR        99 |             0       N/A
